/**
 * MOD-HEAVY Mission One — "Phish in the Wire".
 * Detect → Decide → Contain → Document, then debrief.
 * Defensive / blue-team training only. Every link and attachment is inert:
 * nothing here navigates to, downloads, or executes mission content.
 *
 * Plain script (no ES modules) so it runs from file:// as well as http://.
 * Data: fetch("missions/m1.json"), falling back to window.MODHEAVY_M1_EMBED
 * (js/m1-data.js, generated by tools/build-embed.js).
 */
(function () {
  "use strict";

  const STORAGE_KEY = "modheavy-m1";
  const PHASES = ["detect", "decide", "contain", "document", "debrief"];

  /** @type {object|null} */
  let mission = null;
  let state = freshState();

  const $ = (sel, root = document) => root.querySelector(sel);
  const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));

  function freshState() {
    return {
      phase: null, // null = not started
      startedAt: null,
      finishedAt: null,
      activeMsg: "phish",
      headersOpen: false,
      detailsOpen: false,
      fromRevealed: false,
      linkBlockedNote: false,
      selectedHs: null,
      judged: {}, // hotspotId -> "suspicious" | "benign"
      classId: null,
      justIds: [],
      justSubmitted: false,
      scopeId: null,
      actionIds: [],
      executed: false,
      report: { summary: "", iocs: "", actions: "", recommendation: "" },
      filedAt: null,
    };
  }

  /* ---------- small DOM helpers ---------- */

  function el(tag, cls, text) {
    const node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text !== undefined && text !== null) node.textContent = text;
    return node;
  }

  function clear(node) {
    while (node && node.firstChild) node.removeChild(node.firstChild);
    return node;
  }

  function showView(name) {
    $$(".view").forEach((v) => {
      v.classList.toggle("active", v.dataset.view === name);
    });
    window.scrollTo({ top: 0, behavior: "smooth" });
    try {
      history.replaceState(null, "", "#" + name);
    } catch (_) {
      /* ignore */
    }
  }

  function toast(msg) {
    const t = $("#m1-toast");
    if (!t) return;
    t.hidden = false;
    t.textContent = msg;
    clearTimeout(toast._t);
    toast._t = setTimeout(() => {
      t.hidden = true;
    }, 2800);
  }

  function fmtElapsed(ms) {
    const s = Math.max(0, Math.floor(ms / 1000));
    const m = Math.floor(s / 60);
    return String(m).padStart(2, "0") + ":" + String(s % 60).padStart(2, "0");
  }

  function clamp(n, lo, hi) {
    return Math.max(lo, Math.min(hi, n));
  }

  /* ---------- persistence (local only) ---------- */

  function saveLocal(extra) {
    try {
      const prev = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify(Object.assign(prev, { report: state.report }, extra || {}, { updated: new Date().toISOString() }))
      );
      return true;
    } catch (_) {
      return false;
    }
  }

  function loadLocal() {
    try {
      return JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
    } catch (_) {
      return {};
    }
  }

  /* ---------- progress + timer ---------- */

  function renderProgress() {
    const idx = PHASES.indexOf(state.phase);
    $$(".m1-progress").forEach((host) => {
      clear(host);
      const ol = el("ol", "m1-steps");
      mission.phases.forEach((p, i) => {
        const li = el("li", i < idx ? "done" : i === idx ? "current" : "todo");
        li.appendChild(el("span", "m1-step-num", String(i + 1)));
        li.appendChild(el("span", "m1-step-label", p.label));
        ol.appendChild(li);
      });
      host.appendChild(ol);
      const timer = el("span", "m1-timer");
      timer.setAttribute("aria-label", "Shift clock");
      host.appendChild(timer);
    });
    tickTimer();
  }

  function tickTimer() {
    if (!state.startedAt) return;
    const end = state.finishedAt || Date.now();
    $$(".m1-timer").forEach((t) => {
      t.textContent = "SHIFT " + fmtElapsed(end - state.startedAt);
    });
  }

  /* ---------- phase routing ---------- */

  const RENDER = {
    detect: renderDetect,
    decide: renderDecide,
    contain: renderContain,
    document: renderDocument,
    debrief: renderDebrief,
  };

  function goPhase(phase) {
    state.phase = phase;
    if (!state.startedAt) state.startedAt = Date.now();
    RENDER[phase]();
    renderProgress();
    showView("m1-" + phase);
  }

  /* ---------- briefing ---------- */

  function renderBriefing() {
    const b = mission.briefing;
    $("#m1-brief-title").textContent = mission.title;
    $("#m1-brief-code").textContent = mission.id + " · " + mission.codename + " · " + mission.company;
    const body = clear($("#m1-brief-body"));

    const meta = el("dl", "meta-list");
    [
      ["Ticket", b.alertId],
      ["Reported", b.reportedLocal],
      ["Reporter", b.reporter],
      ["Est. time", mission.estMinutes + " min"],
    ].forEach(([k, v]) => {
      meta.appendChild(el("dt", "", k));
      meta.appendChild(el("dd", "", v));
    });
    body.appendChild(meta);
    body.appendChild(el("p", "", b.context));
    body.appendChild(el("blockquote", "m1-quote", b.reporterQuote));

    body.appendChild(el("h3", "subhead", "Rules of engagement"));
    const ul = el("ul");
    b.roe.forEach((line) => ul.appendChild(el("li", "", line)));
    body.appendChild(ul);

    const obj = el("p");
    obj.appendChild(el("strong", "", "Objective: "));
    obj.appendChild(document.createTextNode(b.objective));
    body.appendChild(obj);

    body.appendChild(comms(b.sam));
    body.appendChild(el("p", "dim tiny", mission.disclaimer));
    refreshBriefingButtons();
  }

  function refreshBriefingButtons() {
    const start = $("#m1-btn-start");
    const restart = $("#m1-btn-restart");
    if (!start) return;
    const inProgress = state.phase && state.phase !== "debrief";
    if (inProgress) {
      const p = mission.phases.find((x) => x.id === state.phase);
      start.textContent = "Resume · " + (p ? p.label : "mission");
    } else if (state.phase === "debrief") {
      start.textContent = "View debrief";
    } else {
      start.textContent = "Accept shift · open reported email";
    }
    if (restart) restart.hidden = !state.phase;
  }

  function comms(text) {
    const box = el("div", "comms");
    box.appendChild(el("span", "comms-who", "SAM · SHIFT LEAD"));
    box.appendChild(el("p", "", text));
    return box;
  }

  function setSam(id, text) {
    const host = $(id);
    if (!host) return;
    clear(host).appendChild(comms(text));
  }

  /* ---------- DETECT ---------- */

  function hotspotDef(id) {
    return mission.detect.hotspots[id];
  }

  /**
   * Inspectable element. A span[role=button] (not <button>) so long inline
   * sentences wrap naturally inside email paragraphs; keyboard-operable.
   */
  function hsButton(id, content, extraCls) {
    const b = el("span", "hs" + (extraCls ? " " + extraCls : ""));
    b.setAttribute("role", "button");
    b.tabIndex = 0;
    b.dataset.hs = id;
    b.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        b.click();
      }
    });
    const verdict = state.judged[id];
    if (verdict === "suspicious") b.classList.add("hs-flag");
    if (verdict === "benign") b.classList.add("hs-clear");
    if (state.selectedHs === id) b.classList.add("hs-active");
    if (typeof content === "string") b.textContent = content;
    else b.appendChild(content);
    b.title = "Inspect: " + hotspotDef(id).label;
    b.addEventListener("click", (e) => {
      e.preventDefault();
      selectHotspot(id);
    });
    return b;
  }

  function renderDetect() {
    setSam("#m1-detect-sam", mission.detect.sam);
    renderInbox();
    renderMessage();
    renderInspector();
    renderEvidence($("#m1-evidence"), true);
    updateDetectGate();
  }

  function renderInbox() {
    const list = clear($("#m1-inbox"));
    mission.detect.inbox.forEach((m) => {
      const li = el("li");
      const b = el("button", "inbox-item" + (m.id === state.activeMsg ? " active" : "") + (m.unread ? " unread" : ""));
      b.type = "button";
      const top = el("span", "inbox-top");
      top.appendChild(el("span", "inbox-from", m.fromName));
      top.appendChild(el("span", "inbox-date", m.dateShort));
      b.appendChild(top);
      b.appendChild(el("span", "inbox-subj", m.subject));
      b.appendChild(el("span", "inbox-prev", m.preview));
      if (m.reported) b.appendChild(el("span", "tag tag-red", "USER-REPORTED"));
      if (m.note) b.appendChild(el("span", "tag tag-cyan", "REFERENCE"));
      b.addEventListener("click", () => {
        state.activeMsg = m.id;
        state.headersOpen = false;
        state.detailsOpen = false;
        renderInbox();
        renderMessage();
      });
      li.appendChild(b);
      list.appendChild(li);
    });
  }

  function currentMessage() {
    return mission.detect.inbox.find((m) => m.id === state.activeMsg) || mission.detect.inbox[0];
  }

  function setStatus(text) {
    const s = $("#m1-status");
    if (!s) return;
    s.textContent = text || "";
    s.classList.toggle("visible", !!text);
  }

  function renderMessage() {
    const m = currentMessage();
    const hs = m.hotspots || {};
    const host = clear($("#m1-message-body"));
    setStatus("");

    if (m.note) host.appendChild(el("p", "mail-note", m.note));
    host.appendChild(el("h2", "mail-subject", m.subject));

    // Header rows
    const head = el("div", "mail-head");
    const fromRow = el("div", "mail-row");
    fromRow.appendChild(el("span", "mail-k", "From"));
    const fromVal = el("span", "mail-v");
    if (hs.from) {
      fromVal.appendChild(hsButton(hs.from, m.fromName, "hs-strong"));
      if (state.fromRevealed || state.detailsOpen) {
        fromVal.appendChild(el("span", "mail-addr revealed", "<" + m.fromAddr + ">"));
      }
    } else {
      fromVal.appendChild(el("strong", "", m.fromName));
      fromVal.appendChild(el("span", "mail-addr", "<" + m.fromAddr + ">"));
    }
    fromRow.appendChild(fromVal);
    const dateVal = el("span", "mail-date");
    if (hs.date) dateVal.appendChild(hsButton(hs.date, m.dateLong));
    else dateVal.textContent = m.dateLong;
    fromRow.appendChild(dateVal);
    head.appendChild(fromRow);

    const toRow = el("div", "mail-row");
    toRow.appendChild(el("span", "mail-k", "To"));
    const toVal = el("span", "mail-v");
    if (hs.to) toVal.appendChild(hsButton(hs.to, m.to));
    else toVal.textContent = m.to;
    toRow.appendChild(toVal);
    head.appendChild(toRow);

    if (state.detailsOpen) {
      const rr = el("div", "mail-row");
      rr.appendChild(el("span", "mail-k", "Reply-To"));
      const rv = el("span", "mail-v");
      if (!m.replyTo) rv.appendChild(el("span", "dim", "(none — replies go to the sender)"));
      else if (hs.replyTo) rv.appendChild(hsButton(hs.replyTo, m.replyTo));
      else rv.textContent = m.replyTo;
      rr.appendChild(rv);
      head.appendChild(rr);
    }
    host.appendChild(head);

    // Toolbar
    const bar = el("div", "mail-toolbar");
    const det = el("button", "btn btn-ghost btn-sm", state.detailsOpen ? "Hide details ▴" : "Show details ▾");
    det.type = "button";
    det.setAttribute("aria-expanded", String(state.detailsOpen));
    det.addEventListener("click", () => {
      state.detailsOpen = !state.detailsOpen;
      renderMessage();
    });
    const raw = el("button", "btn btn-ghost btn-sm", state.headersOpen ? "Hide original headers" : "View original headers");
    raw.type = "button";
    raw.setAttribute("aria-expanded", String(state.headersOpen));
    raw.addEventListener("click", () => {
      state.headersOpen = !state.headersOpen;
      renderMessage();
    });
    bar.appendChild(det);
    bar.appendChild(raw);
    if (m.reported) bar.appendChild(el("span", "tag tag-red", "Reported by m.okafor"));
    host.appendChild(bar);

    if (state.headersOpen) {
      const box = el("div", "raw-headers");
      box.setAttribute("aria-label", "Original message headers");
      m.headers.forEach((blk) => {
        const text = blk.lines.join("\n");
        if (blk.hs) {
          box.appendChild(hsButton(blk.hs, text, "hs-block"));
        } else {
          box.appendChild(el("div", "raw-block", text));
        }
      });
      host.appendChild(box);
    }

    // Body
    const body = el("div", "mail-body");
    m.body.forEach((para) => {
      const p = el("p");
      para.forEach((seg) => {
        if (typeof seg === "string") {
          p.appendChild(document.createTextNode(seg));
        } else if (seg.link) {
          p.appendChild(fakeLink(seg));
        } else if (seg.hs) {
          p.appendChild(hsButton(seg.hs, seg.t, seg.block ? "hs-pre" : ""));
        } else {
          const span = el("span", seg.block ? "pre-line" : "", seg.t);
          p.appendChild(span);
        }
      });
      body.appendChild(p);
    });
    if (state.linkBlockedNote && m.id === "phish") {
      body.appendChild(el("p", "mail-blocked", "⛔ Link not followed — MOD-HEAVY links are inert. Inspect the target instead."));
    }
    host.appendChild(body);

    // Attachments
    if (m.attachments && m.attachments.length) {
      const att = el("div", "mail-attach");
      att.appendChild(el("span", "mail-k", "Attachments"));
      m.attachments.forEach((a) => {
        const chip = el("span", "chip-inner");
        chip.appendChild(el("span", "chip-icon", "▤"));
        chip.appendChild(el("span", "", a.name + " · " + a.size));
        if (a.hs) {
          att.appendChild(hsButton(a.hs, chip, "hs-chip"));
        } else {
          const b = el("button", "chip");
          b.type = "button";
          b.appendChild(chip);
          b.addEventListener("click", () => setStatus("Attachments are inert in the simulation — nothing opens."));
          att.appendChild(b);
        }
      });
      host.appendChild(att);
    }
  }

  /** A link-looking button: never navigates; shows the real target in a status bar on hover/focus. */
  function fakeLink(seg) {
    const b = hsButton(seg.hs, seg.link, "mail-link");
    const show = () => setStatus(seg.href);
    const hide = () => setStatus("");
    b.addEventListener("mouseenter", show);
    b.addEventListener("focus", show);
    b.addEventListener("mouseleave", hide);
    b.addEventListener("blur", hide);
    b.addEventListener("click", () => {
      state.linkBlockedNote = true;
    });
    b.setAttribute("aria-describedby", "m1-status");
    return b;
  }

  function selectHotspot(id) {
    state.selectedHs = id;
    if (id === "from") state.fromRevealed = true;
    if (id === "link") state.linkBlockedNote = true;
    renderMessage();
    renderInspector();
    const again = $('#m1-message-body [data-hs="' + id + '"]');
    if (again) again.focus({ preventScroll: true });
    if (window.matchMedia && window.matchMedia("(max-width: 1000px)").matches) {
      const insp = $("#m1-inspector");
      if (insp && insp.scrollIntoView) insp.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }

  function renderInspector() {
    const host = clear($("#m1-insp-body"));
    const id = state.selectedHs;
    if (!id) {
      host.appendChild(
        el(
          "p",
          "dim",
          "Select anything highlighted in the reported message to inspect it. Hover the link before you click it. Try “Show details” and “View original headers”."
        )
      );
      return;
    }
    const h = hotspotDef(id);
    host.appendChild(el("h3", "insp-title", h.label));
    const dl = el("dl", "insp-dl");
    dl.appendChild(el("dt", "", "What you see"));
    dl.appendChild(el("dd", "", h.surface));
    dl.appendChild(el("dt", "", "Underneath"));
    dl.appendChild(el("dd", "", h.underneath));
    host.appendChild(dl);

    const verdict = state.judged[id];
    if (!verdict) {
      const row = el("div", "insp-actions");
      const sus = el("button", "btn btn-sm btn-flag", "⚑ Suspicious indicator");
      sus.type = "button";
      sus.addEventListener("click", () => judge(id, "suspicious"));
      const ben = el("button", "btn btn-sm btn-ghost", "✓ Not an indicator");
      ben.type = "button";
      ben.addEventListener("click", () => judge(id, "benign"));
      row.appendChild(sus);
      row.appendChild(ben);
      host.appendChild(row);
    } else {
      const right = (verdict === "suspicious") === h.suspicious;
      const fb = el("p", "feedback " + (right ? "good" : "bad"));
      fb.textContent =
        (right ? "Correct — " : "Not quite — ") +
        (h.suspicious ? "this is a suspicious indicator. " : "this isn’t an indicator. ") +
        h.explain;
      host.appendChild(fb);
    }
  }

  function judge(id, verdict) {
    if (state.judged[id]) return;
    state.judged[id] = verdict;
    renderMessage();
    renderInspector();
    renderEvidence($("#m1-evidence"), true);
    updateDetectGate();
    const fb = $("#m1-insp-body .feedback");
    if (fb) {
      fb.tabIndex = -1;
      fb.focus({ preventScroll: true });
    }
  }

  /** Evidence board: judged items (detect view) or flagged indicators only (document view). */
  function renderEvidence(list, showAll) {
    if (!list) return;
    clear(list);
    const ids = Object.keys(mission.detect.hotspots).filter((id) => state.judged[id]);
    const shown = showAll ? ids : ids.filter((id) => state.judged[id] === "suspicious");
    if (!shown.length) {
      list.appendChild(el("li", "dim", showAll ? "Nothing judged yet." : "No indicators flagged in Detect."));
      return;
    }
    shown.forEach((id) => {
      const h = hotspotDef(id);
      const v = state.judged[id];
      const right = (v === "suspicious") === h.suspicious;
      const li = el("li", "ev-item ev-" + v + " " + (right ? "ev-right" : "ev-wrong"));
      li.appendChild(el("span", "ev-icon", v === "suspicious" ? "⚑" : "✓"));
      const txt = el("span", "ev-text");
      txt.appendChild(el("strong", "", h.label));
      if (v === "suspicious" && h.ioc) txt.appendChild(el("span", "ev-ioc", h.ioc));
      li.appendChild(txt);
      if (showAll) li.appendChild(el("span", "ev-mark", right ? "✔" : "✖"));
      list.appendChild(li);
    });
  }

  function updateDetectGate() {
    const total = Object.keys(mission.detect.hotspots).length;
    const n = Object.keys(state.judged).length;
    $("#m1-judged-count").textContent = "(" + n + "/" + total + " judged)";
    const btn = $("#m1-btn-to-decide");
    const gate = $("#m1-detect-gate");
    const min = mission.detect.minJudged;
    btn.disabled = n < min;
    if (n < min) gate.textContent = "Judge at least " + min + " elements to continue.";
    else if (n < total) gate.textContent = total - n + " element(s) unjudged — you can continue, but they score zero.";
    else gate.textContent = "Everything judged. Nice and thorough.";
  }

  function detectScore() {
    let s = 0;
    Object.keys(mission.detect.hotspots).forEach((id) => {
      const h = hotspotDef(id);
      const v = state.judged[id];
      if (v && (v === "suspicious") === h.suspicious) s += h.points;
    });
    return s;
  }

  /* ---------- DECIDE ---------- */

  function feedbackClass(points, max) {
    if (points >= max) return "good";
    if (points > 0) return "ok";
    return "bad";
  }

  function renderChoice(container, options, chosenId, onPick) {
    clear(container);
    const max = Math.max(...options.map((o) => o.points));
    options.forEach((opt) => {
      const b = el("button", "opt");
      b.type = "button";
      b.dataset.id = opt.id;
      b.appendChild(el("span", "", opt.label));
      if (opt.detail) b.appendChild(el("span", "opt-detail", opt.detail));
      if (chosenId) {
        b.disabled = true;
        if (opt.id === chosenId) b.classList.add("selected");
        if (opt.best) b.classList.add("best");
        if (opt.id === chosenId && opt.points === 0) b.classList.add("poor");
      } else {
        b.addEventListener("click", () => onPick(opt));
      }
      container.appendChild(b);
    });
    return max;
  }

  function showFeedback(sel, text, cls) {
    const fb = $(sel);
    if (!text) {
      fb.hidden = true;
      return;
    }
    fb.hidden = false;
    fb.textContent = text;
    fb.className = "feedback " + cls;
  }

  function lockStep(sel, locked) {
    const step = $(sel);
    step.classList.add("step-locked");
    step.classList.toggle("unlocked", !locked);
  }

  function renderDecide() {
    const d = mission.decide;
    setSam("#m1-decide-sam", d.sam);

    // Step 1: classification
    $("#m1-class-prompt").textContent = d.classification.prompt;
    const cmax = renderChoice($("#m1-class-options"), d.classification.options, state.classId, (opt) => {
      state.classId = opt.id;
      renderDecide();
    });
    const cOpt = d.classification.options.find((o) => o.id === state.classId);
    showFeedback("#m1-class-feedback", cOpt && cOpt.feedback, cOpt ? feedbackClass(cOpt.points, cmax) : "");

    // Step 2: justification
    lockStep("#m1-step-just", !state.classId);
    $("#m1-just-prompt").textContent = d.justification.prompt;
    const jl = clear($("#m1-just-options"));
    d.justification.options.forEach((opt) => {
      const lab = el("label", "chk");
      const cb = el("input");
      cb.type = "checkbox";
      cb.value = opt.id;
      cb.checked = state.justIds.includes(opt.id);
      cb.disabled = state.justSubmitted;
      cb.addEventListener("change", () => {
        if (cb.checked) state.justIds.push(opt.id);
        else state.justIds = state.justIds.filter((x) => x !== opt.id);
      });
      lab.appendChild(cb);
      const txt = el("span", "chk-text", opt.label);
      lab.appendChild(txt);
      if (state.justSubmitted) {
        const picked = state.justIds.includes(opt.id);
        if (picked && opt.correct) lab.classList.add("chk-good");
        else if (picked && !opt.correct) {
          lab.classList.add("chk-bad");
          txt.appendChild(el("span", "opt-detail", "✖ " + opt.why));
        } else if (!picked && opt.correct) {
          lab.classList.add("chk-missed");
          txt.appendChild(el("span", "opt-detail", "Missed — this is a real indicator."));
        }
      }
      jl.appendChild(lab);
    });
    const jBtn = $("#m1-btn-just");
    jBtn.hidden = state.justSubmitted;
    if (state.justSubmitted) {
      const j = justScore();
      showFeedback(
        "#m1-just-feedback",
        "Justification: " + j.right + " real indicator(s) selected, " + j.wrong + " non-indicator(s). " +
          (j.wrong ? "Weak evidence dilutes a strong case — stick to what the headers and content prove." : "Clean evidence set."),
        feedbackClass(j.points, d.justification.maxScore)
      );
    } else {
      showFeedback("#m1-just-feedback", "");
    }

    // Logs
    renderLogs();

    // Step 3: scope
    lockStep("#m1-step-scope", !state.justSubmitted);
    $("#m1-scope-prompt").textContent = d.scope.prompt;
    const smax = renderChoice($("#m1-scope-options"), d.scope.options, state.scopeId, (opt) => {
      state.scopeId = opt.id;
      renderDecide();
    });
    const sOpt = d.scope.options.find((o) => o.id === state.scopeId);
    showFeedback("#m1-scope-feedback", sOpt && sOpt.feedback, sOpt ? feedbackClass(sOpt.points, smax) : "");
    $("#m1-decide-continue").hidden = !state.scopeId;
  }

  function renderLogs() {
    const L = mission.decide.logs;
    const host = clear($("#m1-logs"));
    const trace = el("div", "log-block");
    trace.appendChild(el("h3", "subhead", L.trace.title));
    const dl = el("dl", "meta-list");
    L.trace.rows.forEach(([k, v]) => {
      dl.appendChild(el("dt", "", k));
      dl.appendChild(el("dd", "", v));
    });
    trace.appendChild(dl);
    host.appendChild(trace);
    [L.proxy, L.signin].forEach((t) => {
      const blk = el("div", "log-block");
      blk.appendChild(el("h3", "subhead", t.title));
      const wrap = el("div", "table-wrap");
      wrap.tabIndex = 0;
      const table = el("table", "log-table");
      const thead = el("thead");
      const hr = el("tr");
      t.columns.forEach((c) => hr.appendChild(el("th", "", c)));
      thead.appendChild(hr);
      table.appendChild(thead);
      const tb = el("tbody");
      t.rows.forEach((r) => {
        const tr = el("tr");
        r.forEach((c) => tr.appendChild(el("td", "", c)));
        tb.appendChild(tr);
      });
      table.appendChild(tb);
      wrap.appendChild(table);
      blk.appendChild(wrap);
      host.appendChild(blk);
    });
    host.appendChild(el("p", "dim tiny", L.hint));
  }

  function justScore() {
    const J = mission.decide.justification;
    let right = 0;
    let wrong = 0;
    J.options.forEach((o) => {
      if (!state.justIds.includes(o.id)) return;
      if (o.correct) right += 1;
      else wrong += 1;
    });
    return { right, wrong, points: clamp((right - wrong) * J.pointsEach, 0, J.maxScore) };
  }

  function decideScore() {
    const d = mission.decide;
    const c = d.classification.options.find((o) => o.id === state.classId);
    const s = d.scope.options.find((o) => o.id === state.scopeId);
    return {
      classification: c ? c.points : 0,
      justification: state.justSubmitted ? justScore().points : 0,
      scope: s ? s.points : 0,
    };
  }

  /* ---------- CONTAIN ---------- */

  function renderContain() {
    const C = mission.contain;
    setSam("#m1-contain-sam", C.sam);
    $("#m1-contain-prompt").textContent = C.prompt;
    const list = clear($("#m1-actions"));
    C.actions.forEach((a) => {
      const lab = el("label", "chk chk-card");
      const cb = el("input");
      cb.type = "checkbox";
      cb.value = a.id;
      cb.checked = state.actionIds.includes(a.id);
      cb.disabled = state.executed;
      cb.addEventListener("change", () => {
        if (cb.checked) state.actionIds.push(a.id);
        else state.actionIds = state.actionIds.filter((x) => x !== a.id);
        $("#m1-btn-execute").disabled = state.actionIds.length === 0;
      });
      lab.appendChild(cb);
      const txt = el("span", "chk-text", a.label);
      if (a.detail) txt.appendChild(el("span", "opt-detail", a.detail));
      if (state.executed) {
        const picked = state.actionIds.includes(a.id);
        let note = "";
        if (picked && a.kind === "required") {
          lab.classList.add("chk-good");
          note = "+" + a.points + " · " + a.feedback;
        } else if (picked && a.kind === "neutral") {
          lab.classList.add("chk-neutral");
          note = "±0 · " + a.feedback;
        } else if (picked) {
          lab.classList.add("chk-bad");
          note = a.points + " · " + a.feedback;
        } else if (a.kind === "required") {
          lab.classList.add("chk-missed");
          note = "Missed (+" + a.points + " available) · " + a.feedback;
        }
        if (note) txt.appendChild(el("span", "opt-note", note));
      }
      lab.appendChild(txt);
      list.appendChild(lab);
    });

    const exec = $("#m1-btn-execute");
    exec.hidden = state.executed;
    exec.disabled = state.actionIds.length === 0;

    const res = $("#m1-contain-results");
    res.hidden = !state.executed;
    if (state.executed) {
      const log = clear($("#m1-contain-log"));
      containLogLines().forEach((line) => {
        log.appendChild(el("li", "log-line log-" + line.cls, line.text));
      });
      const sc = containScore();
      showFeedback(
        "#m1-contain-feedback",
        "Containment: " + sc + "/" + C.maxScore + ". " +
          (sc >= C.maxScore ? "Every door shut, nothing broken." : "Check the missed and penalised steps above."),
        feedbackClass(sc, C.maxScore)
      );
    }
    $("#m1-contain-continue").hidden = !state.executed;
  }

  function containLogLines() {
    const lines = [];
    mission.contain.actions.forEach((a) => {
      const picked = state.actionIds.includes(a.id);
      if (picked) {
        const cls = a.kind === "required" ? "ok" : a.kind === "neutral" ? "info" : "bad";
        lines.push({ cls, text: "▸ " + a.label + " — " + a.result });
      } else if (a.kind === "required" && a.missed) {
        lines.push({ cls: "miss", text: "✖ NOT DONE: " + a.label + " — " + a.missed });
      }
    });
    return lines;
  }

  function containScore() {
    let s = 0;
    mission.contain.actions.forEach((a) => {
      if (state.actionIds.includes(a.id)) s += a.points;
    });
    return clamp(s, 0, mission.contain.maxScore);
  }

  /* ---------- DOCUMENT ---------- */

  function renderDocument() {
    const D = mission.document;
    setSam("#m1-doc-sam", D.sam);
    const form = clear($("#m1-report-fields"));
    D.fields.forEach((f) => {
      const id = "m1-field-" + f.id;
      const lab = el("label", "field-label", f.label);
      lab.htmlFor = id;
      const ta = el("textarea", "notes");
      ta.id = id;
      ta.rows = f.rows;
      ta.maxLength = 2000;
      ta.placeholder = f.placeholder;
      ta.value = state.report[f.id] || "";
      ta.addEventListener("input", () => {
        state.report[f.id] = ta.value;
        clearTimeout(renderDocument._save);
        renderDocument._save = setTimeout(() => saveLocal({ finished: false }), 400);
      });
      const wrap = el("div", "field");
      wrap.appendChild(lab);
      wrap.appendChild(ta);
      form.appendChild(wrap);
    });
    renderEvidence($("#m1-doc-evidence"), false);
    const log = clear($("#m1-doc-actions"));
    const picked = mission.contain.actions.filter((a) => state.actionIds.includes(a.id));
    if (!picked.length) log.appendChild(el("li", "dim", "No containment executed."));
    picked.forEach((a) => log.appendChild(el("li", "", a.label)));
    $("#m1-doc-error").hidden = true;
  }

  function normalize(text) {
    return String(text || "")
      .toLowerCase()
      .replace(/\[\.\]|\(\.\)|\{\.\}|\[dot\]/g, ".")
      .replace(/\[@\]|\[at\]/g, "@")
      .replace(/\[:\]/g, ":")
      .replace(/hxxp/g, "http");
  }

  function keyHit(key, text) {
    return key.match.every((group) =>
      group.some((term) => {
        try {
          return new RegExp(term, "i").test(text);
        } catch (_) {
          return text.indexOf(term) !== -1;
        }
      })
    );
  }

  function reportScore() {
    const out = { total: 0, fields: [] };
    mission.document.fields.forEach((f) => {
      const text = normalize(state.report[f.id]);
      let pts = 0;
      const hits = [];
      const misses = [];
      f.keys.forEach((k) => {
        if (keyHit(k, text)) {
          pts += k.points;
          hits.push(k);
        } else {
          misses.push(k);
        }
      });
      pts = Math.min(pts, f.max);
      out.total += pts;
      out.fields.push({ id: f.id, label: f.label, points: pts, max: f.max, hits, misses });
    });
    return out;
  }

  function fileReport() {
    const empty = mission.document.fields.filter((f) => !(state.report[f.id] || "").trim());
    if (empty.length) {
      const err = $("#m1-doc-error");
      err.hidden = false;
      err.textContent = "Fill every section before filing (missing: " + empty.map((f) => f.label).join(", ") + ").";
      return;
    }
    state.filedAt = new Date();
    state.finishedAt = Date.now();
    goPhase("debrief");
  }

  /* ---------- DEBRIEF ---------- */

  function scores() {
    const d = decideScore();
    const r = reportScore();
    const detect = detectScore();
    const decide = d.classification + d.justification + d.scope;
    const contain = containScore();
    return { detect, decide, decideParts: d, contain, report: r, total: detect + decide + contain + r.total };
  }

  function reportText() {
    const cls = mission.decide.classification.options.find((o) => o.id === state.classId);
    const scope = mission.decide.scope.options.find((o) => o.id === state.scopeId);
    const when = (state.filedAt || new Date()).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
    const sec = (title, body) => title + "\n" + "-".repeat(title.length) + "\n" + (body || "(blank)").trim() + "\n";
    return [
      "MOD-HEAVY · CyberLabs Incident Report (SIMULATED TRAINING)",
      "Ticket: " + mission.briefing.alertId + " · " + mission.title,
      "Client: " + mission.company,
      "Classification: " + (cls ? cls.label : "—"),
      "Scope: " + (scope ? scope.label : "—"),
      "Filed: " + when + " (local)",
      "",
      sec("SUMMARY", state.report.summary),
      sec("INDICATORS OF COMPROMISE", state.report.iocs),
      sec("ACTIONS TAKEN", state.report.actions),
      sec("RECOMMENDATION", state.report.recommendation),
      "All indicators are fictional (.example domains, documentation-range IPs).",
    ].join("\n");
  }

  function addRow(tbody, label, pts, max, note) {
    const tr = el("tr");
    tr.appendChild(el("th", "", label));
    tr.appendChild(el("td", "score-cell", pts + " / " + max));
    tr.appendChild(el("td", "dim", note));
    tbody.appendChild(tr);
  }

  function renderDebrief() {
    const S = scores();
    const DB = mission.debrief;
    $("#m1-score-num").textContent = S.total + "/" + DB.maxScore;
    const bands = DB.scoreBands.slice().sort((a, b) => b.min - a.min);
    const band = bands.find((b) => S.total >= b.min) || bands[bands.length - 1];
    $("#m1-score-label").textContent = band.label;
    $("#m1-score-note").textContent = band.note;
    $("#m1-elapsed").textContent =
      state.startedAt && state.finishedAt ? "Shift time " + fmtElapsed(state.finishedAt - state.startedAt) : "";

    const tb = clear($("#m1-breakdown"));
    const total = Object.keys(mission.detect.hotspots).length;
    const right = Object.keys(mission.detect.hotspots).filter((id) => {
      const v = state.judged[id];
      return v && (v === "suspicious") === hotspotDef(id).suspicious;
    }).length;
    addRow(tb, "Detect", S.detect, mission.detect.maxScore, right + "/" + total + " elements judged correctly");
    addRow(
      tb,
      "Decide",
      S.decide,
      mission.decide.maxScore,
      "classification " + S.decideParts.classification + " · evidence " + S.decideParts.justification + " · scope " + S.decideParts.scope
    );
    const missedReq = mission.contain.actions.filter((a) => a.kind === "required" && !state.actionIds.includes(a.id));
    const penal = mission.contain.actions.filter((a) => a.points < 0 && state.actionIds.includes(a.id));
    addRow(tb, "Contain", S.contain, mission.contain.maxScore, missedReq.length + " missed · " + penal.length + " penalised");
    addRow(tb, "Document", S.report.total, mission.document.maxScore, S.report.fields.map((f) => f.label.split(" ")[0] + " " + f.points + "/" + f.max).join(" · "));

    // Gaps
    const gaps = clear($("#m1-gaps"));
    const addGap = (text) => gaps.appendChild(el("li", "", text));
    const unjudged = [];
    Object.keys(mission.detect.hotspots).forEach((id) => {
      const h = hotspotDef(id);
      const v = state.judged[id];
      if (!v) unjudged.push(h.label + (h.suspicious ? " ⚑" : ""));
      else if ((v === "suspicious") !== h.suspicious) addGap("Detect · misjudged: " + h.label + " — " + h.explain);
    });
    if (unjudged.length) addGap("Detect · never judged (⚑ = real indicator): " + unjudged.join(", "));
    const cOpt = mission.decide.classification.options.find((o) => o.id === state.classId);
    if (cOpt && !cOpt.best) addGap("Decide · classification: " + cOpt.feedback);
    const sOpt = mission.decide.scope.options.find((o) => o.id === state.scopeId);
    if (sOpt && !sOpt.best) addGap("Decide · scope: " + sOpt.feedback);
    missedReq.forEach((a) => addGap("Contain · missed: " + a.label + " — " + a.missed));
    penal.forEach((a) => addGap("Contain · " + a.points + ": " + a.label + " — " + a.feedback));
    S.report.fields.forEach((f) => {
      if (f.points >= f.max) return;
      addGap("Report · " + f.label + " — missing: " + f.misses.map((k) => k.label).join("; "));
    });
    if (!gaps.children.length) addGap("No gaps. Sam has nothing to add.");

    $("#m1-report-preview").textContent = reportText();

    // Story
    $("#m1-hook-title").textContent = DB.hook.title;
    $("#m1-hook-body").textContent = DB.hook.body;
    const pass = S.total >= DB.passScore;
    $("#m1-lore-eyebrow").textContent = pass ? "Unlocked · Lore crumb" : "Locked · Lore crumb";
    $("#m1-lore-title").textContent = pass ? DB.loreUnlock.title : "Evidence locker — sealed";
    $("#m1-lore-body").textContent = pass ? DB.loreUnlock.body : DB.lockedHint;

    saveLocal({
      finished: true,
      score: S.total,
      band: band.label,
      loreUnlocked: pass,
    });
  }

  function downloadReport() {
    try {
      const blob = new Blob([reportText()], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = el("a");
      a.href = url;
      a.download = "modheavy-" + mission.briefing.alertId + "-report.txt";
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
      toast("Report downloaded (local file).");
    } catch (_) {
      toast("Download blocked — copy the preview instead.");
    }
  }

  function copyReport() {
    const text = reportText();
    const fallback = () => {
      const ta = el("textarea");
      ta.value = text;
      ta.setAttribute("readonly", "");
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      let ok = false;
      try {
        ok = document.execCommand("copy");
      } catch (_) {
        ok = false;
      }
      ta.remove();
      toast(ok ? "Report copied." : "Copy blocked — select the preview text manually.");
    };
    if (navigator.clipboard && window.isSecureContext) {
      navigator.clipboard.writeText(text).then(() => toast("Report copied."), fallback);
    } else {
      fallback();
    }
  }

  /* ---------- lifecycle ---------- */

  function restart() {
    state = freshState();
    renderBriefing();
    showView("m1-briefing");
  }

  function startOrResume() {
    if (state.phase) goPhase(state.phase);
    else goPhase("detect");
  }

  function bind() {
    const on = (sel, fn) => {
      const n = $(sel);
      if (n) n.addEventListener("click", fn);
    };
    on("#m1-btn-start", startOrResume);
    on("#m1-btn-restart", restart);
    on("#m1-btn-to-decide", () => goPhase("decide"));
    on("#m1-btn-just", () => {
      if (!state.justIds.length) {
        showFeedback("#m1-just-feedback", "Select at least one observation first.", "ok");
        return;
      }
      state.justSubmitted = true;
      renderDecide();
    });
    on("#m1-btn-to-contain", () => goPhase("contain"));
    on("#m1-btn-execute", () => {
      if (!state.actionIds.length) return;
      state.executed = true;
      renderContain();
    });
    on("#m1-btn-to-document", () => goPhase("document"));
    on("#m1-btn-file", fileReport);
    on("#m1-btn-download", downloadReport);
    on("#m1-btn-copy", copyReport);
    on("#m1-btn-replay", restart);
    $$("[data-m1-back]").forEach((b) =>
      b.addEventListener("click", () => {
        const target = b.getAttribute("data-m1-back");
        if (target === "briefing") {
          refreshBriefingButtons();
          showView("m1-briefing");
        } else {
          goPhase(target);
        }
      })
    );

    // Hub/menu links into the briefing (navigation itself is handled by main.js data-nav).
    document.addEventListener("click", (e) => {
      const t = e.target && e.target.nodeType === 3 ? e.target.parentElement : e.target;
      if (!t || !t.closest) return;
      const nav = t.closest('[data-nav="m1-briefing"]');
      if (nav && mission) refreshBriefingButtons();
    });
  }

  async function loadMission() {
    // file:// blocks fetch of local JSON (and logs CORS errors) — go straight to the embed.
    if (location.protocol === "file:") {
      mission = window.MODHEAVY_M1_EMBED || null;
      return;
    }
    try {
      const res = await fetch("missions/m1.json", { cache: "no-store" });
      if (res.ok) {
        mission = await res.json();
        return;
      }
    } catch (_) {
      /* file:// or offline — use embed */
    }
    mission = window.MODHEAVY_M1_EMBED || null;
  }

  async function init() {
    bind();
    await loadMission();
    if (!mission) {
      const body = $("#m1-brief-body");
      if (body) body.textContent = "Mission One data failed to load. Check that js/m1-data.js is present next to index.html.";
      return;
    }
    const stored = loadLocal();
    if (stored.report && !stored.finished) state.report = Object.assign(state.report, stored.report);
    renderBriefing();
    setInterval(tickTimer, 1000);
    // Deep links into mid-mission views restart at the briefing (progress is in memory only).
    const hash = (location.hash || "").replace(/^#/, "");
    if (/^m1-/.test(hash)) showView("m1-briefing");
  }

  // Exposed for debugging / automated smoke tests only.
  window.MODHEAVY_M1 = {
    get state() {
      return state;
    },
    get mission() {
      return mission;
    },
    scores: () => (mission ? scores() : null),
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
