/**
 * MOD-HEAVY Mission Two — "Ghost Process" (poisoned AI coding assistant).
 * Detect → Decide → Contain → Document, then debrief.
 * Defensive / blue-team training only. Every artifact is display-only text:
 * nothing here runs, downloads, or connects to anything in the mission data.
 *
 * Plain script (no ES modules) so it runs from file:// as well as http://.
 * Data: fetch("missions/m2.json"), falling back to window.MODHEAVY_M2_EMBED
 * (js/m2-data.js, generated by tools/build-embed.js).
 *
 * Mirrors js/m1.js. Differences: Detect is an evidence console (process table,
 * agent transcripts, egress log, PR diff) instead of a mail client, and Decide
 * has several scope questions (systems + secrets).
 */
(function () {
  "use strict";

  const STORAGE_KEY = "modheavy-m2";
  const PHASES = ["detect", "decide", "contain", "document", "debrief"];

  /** @type {object|null} */
  let mission = null;
  let state = freshState();

  const $ = (sel, root = document) => root.querySelector(sel);
  const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));

  function freshState() {
    return {
      phase: null, // null = not started
      startedAt: null,
      finishedAt: null,
      activeSource: "proc",
      visited: { proc: true },
      selectedHs: null,
      judged: {}, // hotspotId -> "suspicious" | "benign"
      classId: null,
      justIds: [],
      justSubmitted: false,
      scopeIds: {}, // scope question id -> option id
      actionIds: [],
      executed: false,
      report: { summary: "", iocs: "", actions: "", recommendation: "" },
      filedAt: null,
    };
  }

  /* ---------- small DOM helpers ---------- */

  function el(tag, cls, text) {
    const node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text !== undefined && text !== null) node.textContent = text;
    return node;
  }

  function clear(node) {
    while (node && node.firstChild) node.removeChild(node.firstChild);
    return node;
  }

  function showView(name) {
    $$(".view").forEach((v) => {
      v.classList.toggle("active", v.dataset.view === name);
    });
    window.scrollTo({ top: 0, behavior: "smooth" });
    try {
      history.replaceState(null, "", "#" + name);
    } catch (_) {
      /* ignore */
    }
  }

  function toast(msg) {
    const t = $("#m2-toast");
    if (!t) return;
    t.hidden = false;
    t.textContent = msg;
    clearTimeout(toast._t);
    toast._t = setTimeout(() => {
      t.hidden = true;
    }, 2800);
  }

  function fmtElapsed(ms) {
    const s = Math.max(0, Math.floor(ms / 1000));
    const m = Math.floor(s / 60);
    return String(m).padStart(2, "0") + ":" + String(s % 60).padStart(2, "0");
  }

  function clamp(n, lo, hi) {
    return Math.max(lo, Math.min(hi, n));
  }

  /* ---------- persistence (local only) ---------- */

  function saveLocal(extra) {
    try {
      const prev = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify(Object.assign(prev, { report: state.report }, extra || {}, { updated: new Date().toISOString() }))
      );
      return true;
    } catch (_) {
      return false;
    }
  }

  function loadLocal() {
    try {
      return JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
    } catch (_) {
      return {};
    }
  }

  /* ---------- progress + timer ---------- */

  function renderProgress() {
    const idx = PHASES.indexOf(state.phase);
    $$(".m2-progress").forEach((host) => {
      clear(host);
      const ol = el("ol", "m1-steps");
      mission.phases.forEach((p, i) => {
        const li = el("li", i < idx ? "done" : i === idx ? "current" : "todo");
        li.appendChild(el("span", "m1-step-num", String(i + 1)));
        li.appendChild(el("span", "m1-step-label", p.label));
        ol.appendChild(li);
      });
      host.appendChild(ol);
      const timer = el("span", "m2-timer");
      timer.setAttribute("aria-label", "Shift clock");
      host.appendChild(timer);
    });
    tickTimer();
  }

  function tickTimer() {
    if (!state.startedAt) return;
    const end = state.finishedAt || Date.now();
    $$(".m2-timer").forEach((t) => {
      t.textContent = "SHIFT " + fmtElapsed(end - state.startedAt);
    });
  }

  /* ---------- phase routing ---------- */

  const RENDER = {
    detect: renderDetect,
    decide: renderDecide,
    contain: renderContain,
    document: renderDocument,
    debrief: renderDebrief,
  };

  function goPhase(phase) {
    state.phase = phase;
    if (!state.startedAt) state.startedAt = Date.now();
    RENDER[phase]();
    renderProgress();
    showView("m2-" + phase);
  }

  /* ---------- briefing ---------- */

  function renderBriefing() {
    const b = mission.briefing;
    $("#m2-brief-title").textContent = mission.title;
    $("#m2-brief-code").textContent = mission.id + " · " + mission.codename + " · " + mission.company;
    const body = clear($("#m2-brief-body"));

    const meta = el("dl", "meta-list");
    [
      ["Ticket", b.alertId],
      ["Raised", b.reportedLocal],
      ["Source", b.reporter],
      ["Est. time", mission.estMinutes + " min"],
    ].forEach(([k, v]) => {
      meta.appendChild(el("dt", "", k));
      meta.appendChild(el("dd", "", v));
    });
    body.appendChild(meta);
    body.appendChild(el("p", "", b.context));
    body.appendChild(el("blockquote", "m1-quote", b.reporterQuote));

    body.appendChild(el("h3", "subhead", "Rules of engagement"));
    const ul = el("ul");
    b.roe.forEach((line) => ul.appendChild(el("li", "", line)));
    body.appendChild(ul);

    const obj = el("p");
    obj.appendChild(el("strong", "", "Objective: "));
    obj.appendChild(document.createTextNode(b.objective));
    body.appendChild(obj);

    body.appendChild(comms(b.sam));
    body.appendChild(el("p", "dim tiny", mission.disclaimer));
    refreshBriefingButtons();
  }

  function refreshBriefingButtons() {
    const start = $("#m2-btn-start");
    const restart = $("#m2-btn-restart");
    if (!start || !mission) return;
    const inProgress = state.phase && state.phase !== "debrief";
    if (inProgress) {
      const p = mission.phases.find((x) => x.id === state.phase);
      start.textContent = "Resume · " + (p ? p.label : "mission");
    } else if (state.phase === "debrief") {
      start.textContent = "View debrief";
    } else {
      start.textContent = "Accept shift · open evidence";
    }
    if (restart) restart.hidden = !state.phase;
  }

  function comms(text) {
    const box = el("div", "comms");
    box.appendChild(el("span", "comms-who", "SAM · SHIFT LEAD"));
    box.appendChild(el("p", "", text));
    return box;
  }

  function setSam(id, text) {
    const host = $(id);
    if (!host) return;
    clear(host).appendChild(comms(text));
  }

  /* ---------- DETECT ---------- */

  function hotspotDef(id) {
    return mission.detect.hotspots[id];
  }

  function sourceDef(id) {
    return mission.detect.sources.find((s) => s.id === id) || mission.detect.sources[0];
  }

  /** Make any node an inspectable, keyboard-operable hotspot. */
  function markHs(node, id) {
    node.setAttribute("role", "button");
    node.tabIndex = 0;
    node.dataset.hs = id;
    const verdict = state.judged[id];
    if (verdict === "suspicious") node.classList.add("hs-flag");
    if (verdict === "benign") node.classList.add("hs-clear");
    if (state.selectedHs === id) node.classList.add("hs-active");
    node.title = "Inspect: " + hotspotDef(id).label;
    node.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        node.click();
      }
    });
    node.addEventListener("click", (e) => {
      e.preventDefault();
      selectHotspot(id);
    });
    return node;
  }

  function hsButton(id, content, extraCls) {
    const b = el("span", "hs" + (extraCls ? " " + extraCls : ""));
    if (typeof content === "string") b.textContent = content;
    else b.appendChild(content);
    return markHs(b, id);
  }

  /** A data cell: plain string or { t, hs }. */
  function cellContent(c) {
    if (c && typeof c === "object") return c.hs ? hsButton(c.hs, c.t) : document.createTextNode(c.t);
    return document.createTextNode(String(c));
  }

  function renderDetect() {
    setSam("#m2-detect-sam", mission.detect.sam);
    renderSources();
    renderSource();
    renderInspector();
    renderEvidence($("#m2-evidence"), true);
    updateDetectGate();
  }

  function hotspotsIn(sourceId) {
    return Object.keys(mission.detect.hotspots).filter((id) => hotspotDef(id).source === sourceId);
  }

  function renderSources() {
    const list = clear($("#m2-sources"));
    mission.detect.sources.forEach((s) => {
      const li = el("li");
      const b = el(
        "button",
        "inbox-item" + (s.id === state.activeSource ? " active" : "") + (state.visited[s.id] ? "" : " unread")
      );
      b.type = "button";
      b.dataset.source = s.id;
      const top = el("span", "inbox-top");
      top.appendChild(el("span", "inbox-from", s.label));
      b.appendChild(top);
      b.appendChild(el("span", "inbox-subj", s.sub));
      const ids = hotspotsIn(s.id);
      if (ids.length) {
        const n = ids.filter((id) => state.judged[id]).length;
        b.appendChild(el("span", "inbox-prev", n + "/" + ids.length + " items judged"));
      } else {
        b.appendChild(el("span", "inbox-prev", "Comparison only"));
      }
      if (s.reference) b.appendChild(el("span", "tag tag-cyan", "REFERENCE"));
      else if (s.tag) b.appendChild(el("span", "tag " + (s.tag === "ALERT HOST" ? "tag-red" : "tag-cyan"), s.tag));
      b.addEventListener("click", () => openSource(s.id));
      li.appendChild(b);
      list.appendChild(li);
    });
  }

  function openSource(id) {
    state.activeSource = id;
    state.visited[id] = true;
    renderSources();
    renderSource();
  }

  function renderMeta(rows) {
    const dl = el("dl", "meta-list m2-meta");
    rows.forEach(([k, v]) => {
      dl.appendChild(el("dt", "", k));
      const dd = el("dd");
      dd.appendChild(cellContent(v));
      dl.appendChild(dd);
    });
    return dl;
  }

  function renderTable(columns, rows) {
    const wrap = el("div", "table-wrap");
    wrap.tabIndex = 0;
    const table = el("table", "log-table");
    const thead = el("thead");
    const hr = el("tr");
    columns.forEach((c) => hr.appendChild(el("th", "", c)));
    thead.appendChild(hr);
    table.appendChild(thead);
    const tb = el("tbody");
    rows.forEach((r) => {
      const tr = el("tr");
      const cells = Array.isArray(r) ? r : r.cells;
      cells.forEach((c) => {
        const td = el("td");
        const text = c && typeof c === "object" ? c.t : String(c);
        if (text.length > 22) td.classList.add("m2-wrap");
        td.appendChild(cellContent(c));
        tr.appendChild(td);
      });
      if (!Array.isArray(r) && r.hs) {
        tr.classList.add("hs-row");
        markHs(tr, r.hs);
      }
      tb.appendChild(tr);
    });
    table.appendChild(tb);
    wrap.appendChild(table);
    return wrap;
  }

  function renderTerminal(lines) {
    const box = el("div", "m2-term");
    box.setAttribute("aria-label", "Agent session transcript");
    lines.forEach((line) => {
      if (line && typeof line === "object") {
        box.appendChild(hsButton(line.hs, line.t, "hs-block m2-term-hs"));
      } else {
        box.appendChild(el("div", "m2-term-line" + (/^==/.test(line) ? " m2-term-head" : ""), line || "\u00a0"));
      }
    });
    return box;
  }

  function renderDiff(files) {
    const box = el("div", "m2-diff");
    files.forEach((f) => {
      const file = el("div", "m2-diff-file");
      file.appendChild(el("div", "m2-diff-path", f.path));
      f.hunks.forEach((h) => {
        file.appendChild(el("div", "m2-diff-hunk", h.head));
        h.lines.forEach(([op, text, hs]) => {
          const cls = "m2-diff-line " + (op === "+" ? "m2-add" : op === "-" ? "m2-del" : "m2-ctx");
          const content = op + " " + text;
          if (hs) file.appendChild(hsButton(hs, content, "hs-block " + cls));
          else file.appendChild(el("div", cls, content));
        });
      });
      box.appendChild(file);
    });
    return box;
  }

  function renderSource() {
    const s = sourceDef(state.activeSource);
    const host = clear($("#m2-source-body"));
    if (s.note) host.appendChild(el("p", "mail-note", s.note));
    host.appendChild(el("h2", "mail-subject", s.title));
    if (s.meta) host.appendChild(renderMeta(s.meta));
    if (s.kind === "table") host.appendChild(renderTable(s.columns, s.rows));
    else if (s.kind === "terminal") host.appendChild(renderTerminal(s.lines));
    else if (s.kind === "diff") host.appendChild(renderDiff(s.files));
    host.appendChild(
      el(
        "p",
        "dim tiny",
        s.reference
          ? "Known-good comparison. Nothing here to judge — look for what’s missing compared with session 7f3a."
          : "Display only — nothing here runs or connects. Select highlighted items to inspect them."
      )
    );
  }

  function selectHotspot(id) {
    const h = hotspotDef(id);
    state.selectedHs = id;
    if (h.source && h.source !== state.activeSource) {
      state.activeSource = h.source;
      state.visited[h.source] = true;
      renderSources();
    }
    renderSource();
    renderInspector();
    const again = $('#m2-source-body [data-hs="' + id + '"]');
    if (again) again.focus({ preventScroll: true });
    if (window.matchMedia && window.matchMedia("(max-width: 1000px)").matches) {
      const insp = $("#m2-inspector");
      if (insp && insp.scrollIntoView) insp.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }

  function renderInspector() {
    const host = clear($("#m2-insp-body"));
    const id = state.selectedHs;
    if (!id) {
      host.appendChild(
        el(
          "p",
          "dim",
          "Open an evidence source above, then select anything highlighted to inspect it. Compare the two agent transcripts."
        )
      );
      return;
    }
    const h = hotspotDef(id);
    host.appendChild(el("h3", "insp-title", h.label));
    const dl = el("dl", "insp-dl");
    dl.appendChild(el("dt", "", "What you see"));
    dl.appendChild(el("dd", "", h.surface));
    dl.appendChild(el("dt", "", "Underneath"));
    dl.appendChild(el("dd", "", h.underneath));
    host.appendChild(dl);

    const verdict = state.judged[id];
    if (!verdict) {
      const row = el("div", "insp-actions");
      const sus = el("button", "btn btn-sm btn-flag", "⚑ Suspicious indicator");
      sus.type = "button";
      sus.addEventListener("click", () => judge(id, "suspicious"));
      const ben = el("button", "btn btn-sm btn-ghost", "✓ Not an indicator");
      ben.type = "button";
      ben.addEventListener("click", () => judge(id, "benign"));
      row.appendChild(sus);
      row.appendChild(ben);
      host.appendChild(row);
    } else {
      const right = (verdict === "suspicious") === h.suspicious;
      const fb = el("p", "feedback " + (right ? "good" : "bad"));
      fb.textContent =
        (right ? "Correct — " : "Not quite — ") +
        (h.suspicious ? "this is a suspicious indicator. " : "this isn’t an indicator. ") +
        h.explain;
      host.appendChild(fb);
    }
  }

  function judge(id, verdict) {
    if (state.judged[id]) return;
    state.judged[id] = verdict;
    renderSources();
    renderSource();
    renderInspector();
    renderEvidence($("#m2-evidence"), true);
    updateDetectGate();
    const fb = $("#m2-insp-body .feedback");
    if (fb) {
      fb.tabIndex = -1;
      fb.focus({ preventScroll: true });
    }
  }

  /** Evidence board: judged items (detect view, clickable) or flagged indicators only (document view). */
  function renderEvidence(list, showAll) {
    if (!list) return;
    clear(list);
    const ids = Object.keys(mission.detect.hotspots).filter((id) => state.judged[id]);
    const shown = showAll ? ids : ids.filter((id) => state.judged[id] === "suspicious");
    if (!shown.length) {
      list.appendChild(el("li", "dim", showAll ? "Nothing judged yet." : "No indicators flagged in Detect."));
      return;
    }
    shown.forEach((id) => {
      const h = hotspotDef(id);
      const v = state.judged[id];
      const right = (v === "suspicious") === h.suspicious;
      const li = el("li", "ev-item ev-" + v + " " + (right ? "ev-right" : "ev-wrong"));
      li.appendChild(el("span", "ev-icon", v === "suspicious" ? "⚑" : "✓"));
      const txt = el("span", "ev-text");
      txt.appendChild(el("strong", "", h.label));
      if (v === "suspicious" && h.ioc) txt.appendChild(el("span", "ev-ioc", h.ioc));
      li.appendChild(txt);
      if (showAll) {
        li.appendChild(el("span", "ev-mark", right ? "✔" : "✖"));
        li.classList.add("ev-jump");
        li.tabIndex = 0;
        li.setAttribute("role", "button");
        li.title = "Show in " + sourceDef(h.source).label;
        li.addEventListener("click", () => selectHotspot(id));
        li.addEventListener("keydown", (e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            selectHotspot(id);
          }
        });
      }
      list.appendChild(li);
    });
  }

  function updateDetectGate() {
    const total = Object.keys(mission.detect.hotspots).length;
    const n = Object.keys(state.judged).length;
    $("#m2-judged-count").textContent = "(" + n + "/" + total + " judged)";
    const btn = $("#m2-btn-to-decide");
    const gate = $("#m2-detect-gate");
    const min = mission.detect.minJudged;
    btn.disabled = n < min;
    if (n < min) gate.textContent = "Judge at least " + min + " items to continue. Check every source.";
    else if (n < total) gate.textContent = total - n + " item(s) unjudged — you can continue, but they score zero.";
    else gate.textContent = "Everything judged. Nice and thorough.";
  }

  function detectScore() {
    let s = 0;
    Object.keys(mission.detect.hotspots).forEach((id) => {
      const h = hotspotDef(id);
      const v = state.judged[id];
      if (v && (v === "suspicious") === h.suspicious) s += h.points;
    });
    return s;
  }

  /* ---------- DECIDE ---------- */

  function feedbackClass(points, max) {
    if (points >= max) return "good";
    if (points > 0) return "ok";
    return "bad";
  }

  function renderChoice(container, options, chosenId, onPick) {
    clear(container);
    const max = Math.max(...options.map((o) => o.points));
    options.forEach((opt) => {
      const b = el("button", "opt");
      b.type = "button";
      b.dataset.id = opt.id;
      b.appendChild(el("span", "", opt.label));
      if (opt.detail) b.appendChild(el("span", "opt-detail", opt.detail));
      if (chosenId) {
        b.disabled = true;
        if (opt.id === chosenId) b.classList.add("selected");
        if (opt.best) b.classList.add("best");
        if (opt.id === chosenId && opt.points === 0) b.classList.add("poor");
      } else {
        b.addEventListener("click", () => onPick(opt));
      }
      container.appendChild(b);
    });
    return max;
  }

  function setFeedback(fb, text, cls) {
    if (!fb) return;
    if (!text) {
      fb.hidden = true;
      return;
    }
    fb.hidden = false;
    fb.textContent = text;
    fb.className = "feedback " + cls;
  }

  function showFeedback(sel, text, cls) {
    setFeedback($(sel), text, cls);
  }

  function lockStep(sel, locked) {
    const step = $(sel);
    step.classList.add("step-locked");
    step.classList.toggle("unlocked", !locked);
  }

  function renderDecide() {
    const d = mission.decide;
    setSam("#m2-decide-sam", d.sam);

    // Step 1: classification
    $("#m2-class-prompt").textContent = d.classification.prompt;
    const cmax = renderChoice($("#m2-class-options"), d.classification.options, state.classId, (opt) => {
      state.classId = opt.id;
      renderDecide();
    });
    const cOpt = d.classification.options.find((o) => o.id === state.classId);
    showFeedback("#m2-class-feedback", cOpt && cOpt.feedback, cOpt ? feedbackClass(cOpt.points, cmax) : "");

    // Step 2: justification
    lockStep("#m2-step-just", !state.classId);
    $("#m2-just-prompt").textContent = d.justification.prompt;
    const jl = clear($("#m2-just-options"));
    d.justification.options.forEach((opt) => {
      const lab = el("label", "chk");
      const cb = el("input");
      cb.type = "checkbox";
      cb.value = opt.id;
      cb.checked = state.justIds.includes(opt.id);
      cb.disabled = state.justSubmitted;
      cb.addEventListener("change", () => {
        if (cb.checked) state.justIds.push(opt.id);
        else state.justIds = state.justIds.filter((x) => x !== opt.id);
      });
      lab.appendChild(cb);
      const txt = el("span", "chk-text", opt.label);
      lab.appendChild(txt);
      if (state.justSubmitted) {
        const picked = state.justIds.includes(opt.id);
        if (picked && opt.correct) lab.classList.add("chk-good");
        else if (picked && !opt.correct) {
          lab.classList.add("chk-bad");
          txt.appendChild(el("span", "opt-detail", "✖ " + opt.why));
        } else if (!picked && opt.correct) {
          lab.classList.add("chk-missed");
          txt.appendChild(el("span", "opt-detail", "Missed — this is a real indicator."));
        }
      }
      jl.appendChild(lab);
    });
    const jBtn = $("#m2-btn-just");
    jBtn.hidden = state.justSubmitted;
    if (state.justSubmitted) {
      const j = justScore();
      showFeedback(
        "#m2-just-feedback",
        "Justification: " + j.right + " real indicator(s) selected, " + j.wrong + " non-indicator(s). " +
          (j.wrong ? "Weak evidence dilutes a strong case — stick to what the process, transcript, and logs prove." : "Clean evidence set."),
        feedbackClass(j.points, d.justification.maxScore)
      );
    } else {
      showFeedback("#m2-just-feedback", "");
    }

    // Logs
    renderLogs();

    // Step 3: scope questions (each unlocks after the previous one is answered)
    lockStep("#m2-step-scope", !state.justSubmitted);
    const host = clear($("#m2-scope-host"));
    let open = true;
    d.scopes.forEach((q, i) => {
      if (!open) return;
      const block = el("div", "m2-scope-q");
      block.appendChild(el("h3", "subhead", "Scope " + (i + 1) + " · " + q.label));
      block.appendChild(el("p", "m2-scope-prompt", q.prompt));
      const grid = el("div", "option-grid");
      grid.dataset.scope = q.id;
      grid.setAttribute("role", "group");
      grid.setAttribute("aria-label", q.label + " scope options");
      block.appendChild(grid);
      const fb = el("p", "feedback");
      fb.hidden = true;
      block.appendChild(fb);
      host.appendChild(block);
      const chosen = state.scopeIds[q.id] || null;
      const smax = renderChoice(grid, q.options, chosen, (opt) => {
        state.scopeIds[q.id] = opt.id;
        renderDecide();
      });
      const sOpt = q.options.find((o) => o.id === chosen);
      setFeedback(fb, sOpt && sOpt.feedback, sOpt ? feedbackClass(sOpt.points, smax) : "");
      if (!chosen) open = false;
    });
    $("#m2-decide-continue").hidden = !scopesDone();
  }

  function scopesDone() {
    return mission.decide.scopes.every((q) => state.scopeIds[q.id]);
  }

  function renderLogs() {
    const host = clear($("#m2-logs"));
    mission.decide.logs.forEach((blkDef) => {
      const blk = el("div", "log-block");
      blk.appendChild(el("h3", "subhead", blkDef.title));
      if (blkDef.kind === "meta") blk.appendChild(renderMeta(blkDef.rows));
      else blk.appendChild(renderTable(blkDef.columns, blkDef.rows));
      host.appendChild(blk);
    });
    host.appendChild(el("p", "dim tiny", mission.decide.hint));
  }

  function justScore() {
    const J = mission.decide.justification;
    let right = 0;
    let wrong = 0;
    J.options.forEach((o) => {
      if (!state.justIds.includes(o.id)) return;
      if (o.correct) right += 1;
      else wrong += 1;
    });
    return { right, wrong, points: clamp((right - wrong) * J.pointsEach, 0, J.maxScore) };
  }

  function scopeOption(q) {
    return q.options.find((o) => o.id === state.scopeIds[q.id]) || null;
  }

  function decideScore() {
    const d = mission.decide;
    const c = d.classification.options.find((o) => o.id === state.classId);
    const scopes = d.scopes.map((q) => {
      const o = scopeOption(q);
      return { id: q.id, label: q.label, points: o ? o.points : 0 };
    });
    return {
      classification: c ? c.points : 0,
      justification: state.justSubmitted ? justScore().points : 0,
      scopes,
      scope: scopes.reduce((a, s) => a + s.points, 0),
    };
  }

  /* ---------- CONTAIN ---------- */

  function renderContain() {
    const C = mission.contain;
    setSam("#m2-contain-sam", C.sam);
    $("#m2-contain-prompt").textContent = C.prompt;
    const list = clear($("#m2-actions"));
    C.actions.forEach((a) => {
      const lab = el("label", "chk chk-card");
      const cb = el("input");
      cb.type = "checkbox";
      cb.value = a.id;
      cb.checked = state.actionIds.includes(a.id);
      cb.disabled = state.executed;
      cb.addEventListener("change", () => {
        if (cb.checked) state.actionIds.push(a.id);
        else state.actionIds = state.actionIds.filter((x) => x !== a.id);
        $("#m2-btn-execute").disabled = state.actionIds.length === 0;
      });
      lab.appendChild(cb);
      const txt = el("span", "chk-text", a.label);
      if (a.detail) txt.appendChild(el("span", "opt-detail", a.detail));
      if (state.executed) {
        const picked = state.actionIds.includes(a.id);
        let note = "";
        if (picked && a.kind === "required") {
          lab.classList.add("chk-good");
          note = "+" + a.points + " · " + a.feedback;
        } else if (picked && a.kind === "neutral") {
          lab.classList.add("chk-neutral");
          note = "±0 · " + a.feedback;
        } else if (picked) {
          lab.classList.add("chk-bad");
          note = a.points + " · " + a.feedback;
        } else if (a.kind === "required") {
          lab.classList.add("chk-missed");
          note = "Missed (+" + a.points + " available) · " + a.feedback;
        }
        if (note) txt.appendChild(el("span", "opt-note", note));
      }
      lab.appendChild(txt);
      list.appendChild(lab);
    });

    const exec = $("#m2-btn-execute");
    exec.hidden = state.executed;
    exec.disabled = state.actionIds.length === 0;

    const res = $("#m2-contain-results");
    res.hidden = !state.executed;
    if (state.executed) {
      const log = clear($("#m2-contain-log"));
      containLogLines().forEach((line) => {
        log.appendChild(el("li", "log-line log-" + line.cls, line.text));
      });
      const sc = containScore();
      showFeedback(
        "#m2-contain-feedback",
        "Containment: " + sc + "/" + C.maxScore + ". " +
          (sc >= C.maxScore ? "Every door shut, nothing broken." : "Check the missed and penalised steps above."),
        feedbackClass(sc, C.maxScore)
      );
    }
    $("#m2-contain-continue").hidden = !state.executed;
  }

  function containLogLines() {
    const lines = [];
    mission.contain.actions.forEach((a) => {
      const picked = state.actionIds.includes(a.id);
      if (picked) {
        const cls = a.kind === "required" ? "ok" : a.kind === "neutral" ? "info" : "bad";
        lines.push({ cls, text: "▸ " + a.label + " — " + a.result });
      } else if (a.kind === "required" && a.missed) {
        lines.push({ cls: "miss", text: "✖ NOT DONE: " + a.label + " — " + a.missed });
      }
    });
    return lines;
  }

  function containScore() {
    let s = 0;
    mission.contain.actions.forEach((a) => {
      if (state.actionIds.includes(a.id)) s += a.points;
    });
    return clamp(s, 0, mission.contain.maxScore);
  }

  /* ---------- DOCUMENT ---------- */

  function renderDocument() {
    const D = mission.document;
    setSam("#m2-doc-sam", D.sam);
    const form = clear($("#m2-report-fields"));
    D.fields.forEach((f) => {
      const id = "m2-field-" + f.id;
      const lab = el("label", "field-label", f.label);
      lab.htmlFor = id;
      const ta = el("textarea", "notes");
      ta.id = id;
      ta.rows = f.rows;
      ta.maxLength = 2000;
      ta.placeholder = f.placeholder;
      ta.value = state.report[f.id] || "";
      ta.addEventListener("input", () => {
        state.report[f.id] = ta.value;
        clearTimeout(renderDocument._save);
        renderDocument._save = setTimeout(() => saveLocal({ finished: false }), 400);
      });
      const wrap = el("div", "field");
      wrap.appendChild(lab);
      wrap.appendChild(ta);
      form.appendChild(wrap);
    });
    renderEvidence($("#m2-doc-evidence"), false);
    const log = clear($("#m2-doc-actions"));
    const picked = mission.contain.actions.filter((a) => state.actionIds.includes(a.id));
    if (!picked.length) log.appendChild(el("li", "dim", "No containment executed."));
    picked.forEach((a) => log.appendChild(el("li", "", a.label)));
    $("#m2-doc-error").hidden = true;
  }

  function normalize(text) {
    return String(text || "")
      .toLowerCase()
      .replace(/\[\.\]|\(\.\)|\{\.\}|\[dot\]/g, ".")
      .replace(/\[@\]|\[at\]/g, "@")
      .replace(/\[:\]/g, ":")
      .replace(/hxxp/g, "http");
  }

  function keyHit(key, text) {
    return key.match.every((group) =>
      group.some((term) => {
        try {
          return new RegExp(term, "i").test(text);
        } catch (_) {
          return text.indexOf(term) !== -1;
        }
      })
    );
  }

  function reportScore() {
    const out = { total: 0, fields: [] };
    mission.document.fields.forEach((f) => {
      const text = normalize(state.report[f.id]);
      let pts = 0;
      const hits = [];
      const misses = [];
      f.keys.forEach((k) => {
        if (keyHit(k, text)) {
          pts += k.points;
          hits.push(k);
        } else {
          misses.push(k);
        }
      });
      pts = Math.min(pts, f.max);
      out.total += pts;
      out.fields.push({ id: f.id, label: f.label, points: pts, max: f.max, hits, misses });
    });
    return out;
  }

  function fileReport() {
    const empty = mission.document.fields.filter((f) => !(state.report[f.id] || "").trim());
    if (empty.length) {
      const err = $("#m2-doc-error");
      err.hidden = false;
      err.textContent = "Fill every section before filing (missing: " + empty.map((f) => f.label).join(", ") + ").";
      return;
    }
    state.filedAt = new Date();
    state.finishedAt = Date.now();
    goPhase("debrief");
  }

  /* ---------- DEBRIEF ---------- */

  function scores() {
    const d = decideScore();
    const r = reportScore();
    const detect = detectScore();
    const decide = d.classification + d.justification + d.scope;
    const contain = containScore();
    return { detect, decide, decideParts: d, contain, report: r, total: detect + decide + contain + r.total };
  }

  function reportText() {
    const cls = mission.decide.classification.options.find((o) => o.id === state.classId);
    const when = (state.filedAt || new Date()).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
    const sec = (title, body) => title + "\n" + "-".repeat(title.length) + "\n" + (body || "(blank)").trim() + "\n";
    const scopeLines = mission.decide.scopes.map((q) => {
      const o = scopeOption(q);
      return "Scope (" + q.label.toLowerCase() + "): " + (o ? o.label : "—");
    });
    return [
      "MOD-HEAVY · CyberLabs Incident Report (SIMULATED TRAINING)",
      "Ticket: " + mission.briefing.alertId + " · " + mission.title,
      "Client: " + mission.company,
      "Classification: " + (cls ? cls.label : "—"),
    ]
      .concat(scopeLines)
      .concat([
        "Filed: " + when + " (local)",
        "",
        sec("SUMMARY", state.report.summary),
        sec("INDICATORS OF COMPROMISE", state.report.iocs),
        sec("ACTIONS TAKEN", state.report.actions),
        sec("LESSONS LEARNED", state.report.recommendation),
        "All indicators are fictional (.example domains, documentation-range IPs, SIMULATION hashes, fictional AI model).",
      ])
      .join("\n");
  }

  function addRow(tbody, label, pts, max, note) {
    const tr = el("tr");
    tr.appendChild(el("th", "", label));
    tr.appendChild(el("td", "score-cell", pts + " / " + max));
    tr.appendChild(el("td", "dim", note));
    tbody.appendChild(tr);
  }

  function renderDebrief() {
    const S = scores();
    const DB = mission.debrief;
    $("#m2-score-num").textContent = S.total + "/" + DB.maxScore;
    const bands = DB.scoreBands.slice().sort((a, b) => b.min - a.min);
    const band = bands.find((b) => S.total >= b.min) || bands[bands.length - 1];
    $("#m2-score-label").textContent = band.label;
    $("#m2-score-note").textContent = band.note;
    $("#m2-elapsed").textContent =
      state.startedAt && state.finishedAt ? "Shift time " + fmtElapsed(state.finishedAt - state.startedAt) : "";

    const tb = clear($("#m2-breakdown"));
    const total = Object.keys(mission.detect.hotspots).length;
    const right = Object.keys(mission.detect.hotspots).filter((id) => {
      const v = state.judged[id];
      return v && (v === "suspicious") === hotspotDef(id).suspicious;
    }).length;
    addRow(tb, "Detect", S.detect, mission.detect.maxScore, right + "/" + total + " items judged correctly");
    addRow(
      tb,
      "Decide",
      S.decide,
      mission.decide.maxScore,
      "classification " + S.decideParts.classification + " · evidence " + S.decideParts.justification + " · " +
        S.decideParts.scopes.map((s) => s.label.toLowerCase() + " " + s.points).join(" · ")
    );
    const missedReq = mission.contain.actions.filter((a) => a.kind === "required" && !state.actionIds.includes(a.id));
    const penal = mission.contain.actions.filter((a) => a.points < 0 && state.actionIds.includes(a.id));
    addRow(tb, "Contain", S.contain, mission.contain.maxScore, missedReq.length + " missed · " + penal.length + " penalised");
    addRow(tb, "Document", S.report.total, mission.document.maxScore, S.report.fields.map((f) => f.label.split(" ")[0] + " " + f.points + "/" + f.max).join(" · "));

    // Gaps
    const gaps = clear($("#m2-gaps"));
    const addGap = (text) => gaps.appendChild(el("li", "", text));
    const unjudged = [];
    Object.keys(mission.detect.hotspots).forEach((id) => {
      const h = hotspotDef(id);
      const v = state.judged[id];
      if (!v) unjudged.push(h.label + (h.suspicious ? " ⚑" : ""));
      else if ((v === "suspicious") !== h.suspicious) addGap("Detect · misjudged: " + h.label + " — " + h.explain);
    });
    if (unjudged.length) addGap("Detect · never judged (⚑ = real indicator): " + unjudged.join(", "));
    const cOpt = mission.decide.classification.options.find((o) => o.id === state.classId);
    if (cOpt && !cOpt.best) addGap("Decide · classification: " + cOpt.feedback);
    mission.decide.scopes.forEach((q) => {
      const o = scopeOption(q);
      if (o && !o.best) addGap("Decide · scope (" + q.label.toLowerCase() + "): " + o.feedback);
    });
    missedReq.forEach((a) => addGap("Contain · missed: " + a.label + " — " + a.missed));
    penal.forEach((a) => addGap("Contain · " + a.points + ": " + a.label + " — " + a.feedback));
    S.report.fields.forEach((f) => {
      if (f.points >= f.max) return;
      addGap("Report · " + f.label + " — missing: " + f.misses.map((k) => k.label).join("; "));
    });
    if (!gaps.children.length) addGap("No gaps. Sam has nothing to add.");

    $("#m2-report-preview").textContent = reportText();

    // Story
    $("#m2-hook-title").textContent = DB.hook.title;
    $("#m2-hook-body").textContent = DB.hook.body;
    const pass = S.total >= DB.passScore;
    $("#m2-lore-eyebrow").textContent = pass ? "Unlocked · Lore crumb" : "Locked · Lore crumb";
    $("#m2-lore-title").textContent = pass ? DB.loreUnlock.title : "Evidence locker — sealed";
    $("#m2-lore-body").textContent = pass ? DB.loreUnlock.body : DB.lockedHint;

    saveLocal({
      finished: true,
      score: S.total,
      band: band.label,
      loreUnlocked: pass,
    });
  }

  function downloadReport() {
    try {
      const blob = new Blob([reportText()], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = el("a");
      a.href = url;
      a.download = "modheavy-" + mission.briefing.alertId + "-report.txt";
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
      toast("Report downloaded (local file).");
    } catch (_) {
      toast("Download blocked — copy the preview instead.");
    }
  }

  function copyReport() {
    const text = reportText();
    const fallback = () => {
      const ta = el("textarea");
      ta.value = text;
      ta.setAttribute("readonly", "");
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      let ok = false;
      try {
        ok = document.execCommand("copy");
      } catch (_) {
        ok = false;
      }
      ta.remove();
      toast(ok ? "Report copied." : "Copy blocked — select the preview text manually.");
    };
    if (navigator.clipboard && window.isSecureContext) {
      navigator.clipboard.writeText(text).then(() => toast("Report copied."), fallback);
    } else {
      fallback();
    }
  }

  /* ---------- lifecycle ---------- */

  function restart() {
    state = freshState();
    renderBriefing();
    showView("m2-briefing");
  }

  function startOrResume() {
    if (!mission) return;
    if (state.phase) goPhase(state.phase);
    else goPhase("detect");
  }

  function bind() {
    const on = (sel, fn) => {
      const n = $(sel);
      if (n) n.addEventListener("click", fn);
    };
    on("#m2-btn-start", startOrResume);
    on("#m2-btn-restart", restart);
    on("#m2-btn-to-decide", () => goPhase("decide"));
    on("#m2-btn-just", () => {
      if (!state.justIds.length) {
        showFeedback("#m2-just-feedback", "Select at least one observation first.", "ok");
        return;
      }
      state.justSubmitted = true;
      renderDecide();
    });
    on("#m2-btn-to-contain", () => goPhase("contain"));
    on("#m2-btn-execute", () => {
      if (!state.actionIds.length) return;
      state.executed = true;
      renderContain();
    });
    on("#m2-btn-to-document", () => goPhase("document"));
    on("#m2-btn-file", fileReport);
    on("#m2-btn-download", downloadReport);
    on("#m2-btn-copy", copyReport);
    on("#m2-btn-replay", restart);
    $$("[data-m2-back]").forEach((b) =>
      b.addEventListener("click", () => {
        const target = b.getAttribute("data-m2-back");
        if (target === "briefing") {
          refreshBriefingButtons();
          showView("m2-briefing");
        } else {
          goPhase(target);
        }
      })
    );

    // Hub/menu links into the briefing (navigation itself is handled by main.js data-nav).
    document.addEventListener("click", (e) => {
      const t = e.target && e.target.nodeType === 3 ? e.target.parentElement : e.target;
      if (!t || !t.closest) return;
      const nav = t.closest('[data-nav="m2-briefing"]');
      if (nav && mission) refreshBriefingButtons();
    });
  }

  async function loadMission() {
    // file:// blocks fetch of local JSON (and logs CORS errors) — go straight to the embed.
    if (location.protocol === "file:") {
      mission = window.MODHEAVY_M2_EMBED || null;
      return;
    }
    try {
      const res = await fetch("missions/m2.json", { cache: "no-store" });
      if (res.ok) {
        mission = await res.json();
        return;
      }
    } catch (_) {
      /* offline — use embed */
    }
    mission = window.MODHEAVY_M2_EMBED || null;
  }

  async function init() {
    bind();
    await loadMission();
    if (!mission) {
      const body = $("#m2-brief-body");
      if (body) body.textContent = "Mission Two data failed to load. Check that js/m2-data.js is present next to index.html.";
      return;
    }
    const stored = loadLocal();
    if (stored.report && !stored.finished) state.report = Object.assign(state.report, stored.report);
    renderBriefing();
    setInterval(tickTimer, 1000);
    // Deep links into mid-mission views restart at the briefing (progress is in memory only).
    const hash = (location.hash || "").replace(/^#/, "");
    if (/^m2-/.test(hash)) showView("m2-briefing");
  }

  // Exposed for debugging / automated smoke tests only.
  window.MODHEAVY_M2 = {
    get state() {
      return state;
    },
    get mission() {
      return mission;
    },
    scores: () => (mission ? scores() : null),
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
